window.WORK_PROJECTS = [
  {
    "id": "novonesis-korea",
    "name": "노보네시스",
    "industryId": "bio",
    "industry": "바이오",
    "year": 2026,
    "areaPyeong": 150,
    "address": "서울 서초구 남부순환로 · 옥스포드빌딩 2, 6F",
    "image": "assets/projects/work/bio/novonesis-korea.jpg",
    "imageAlt": "노보네시스 오피스 프로젝트",
    "mediaKind": "photo",
    "detailHref": "project-detail.html"
  },
  {
    "id": "ybrain",
    "name": "와이브레인",
    "industryId": "bio",
    "industry": "바이오",
    "year": 2025,
    "areaPyeong": 180,
    "address": "판교 창업로 · 판교 제2기업성장센터",
    "image": "assets/projects/work/bio/ybrain.jpg",
    "imageAlt": "와이브레인 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "kakao-healthcare",
    "name": "카카오헬스케어",
    "industryId": "bio",
    "industry": "바이오",
    "year": 2024,
    "areaPyeong": 300,
    "address": "판교 판교역로 · 카카오판교아지트",
    "image": "assets/projects/work/bio/kakao-healthcare.jpg",
    "imageAlt": "카카오헬스케어 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "crescom",
    "name": "크레스콤",
    "industryId": "bio",
    "industry": "바이오",
    "year": 2024,
    "areaPyeong": 120,
    "address": "판교 테크노밸리 · 삼환하이펙스",
    "image": "assets/projects/work/bio/crescom.png",
    "imageAlt": "크레스콤 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "axion",
    "name": "액시언",
    "industryId": "semiconductor",
    "industry": "반도체",
    "year": 2026,
    "areaPyeong": 100,
    "address": "판교 판교역로 · 투썬빌딩",
    "image": "assets/projects/work/semiconductor/axion.jpg",
    "imageAlt": "액시언 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "btree",
    "name": "비트리",
    "industryId": "semiconductor",
    "industry": "반도체",
    "year": 2026,
    "areaPyeong": 100,
    "address": "주소 정보 준비 중",
    "image": "assets/projects/btree-transparent.png",
    "imageAlt": "비트리 로고",
    "mediaKind": "logo"
  },
  {
    "id": "apet",
    "name": "에이펫",
    "industryId": "semiconductor",
    "industry": "반도체",
    "year": 2022,
    "areaPyeong": 150,
    "address": "판교 테크노밸리 · 유스페이스",
    "image": "assets/projects/work/semiconductor/apet.png",
    "imageAlt": "에이펫 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "smart-radar-system",
    "name": "스마트레이더시스템",
    "industryId": "semiconductor",
    "industry": "반도체",
    "year": 2023,
    "areaPyeong": 120,
    "address": "분당 야탑동 · 파인디지털사옥",
    "image": "assets/projects/work/semiconductor/smart-radar-system.jpg",
    "imageAlt": "스마트레이더시스템 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "silicon-mitus",
    "name": "실리콘마이터스",
    "industryId": "semiconductor",
    "industry": "반도체",
    "year": 2023,
    "areaPyeong": 200,
    "address": "판교 테크노밸리 · 유스페이스",
    "image": "assets/projects/work/semiconductor/silicon-mitus.jpg",
    "imageAlt": "실리콘마이터스 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "durian-it",
    "name": "두리안정보기술",
    "industryId": "it",
    "industry": "IT",
    "year": 2024,
    "areaPyeong": 110,
    "address": "판교 테크노밸리 · 우림W시티",
    "image": "assets/projects/work/it/durian-it.jpg",
    "imageAlt": "두리안정보기술 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "secrab",
    "name": "씨크랩",
    "industryId": "it",
    "industry": "IT",
    "year": 2024,
    "areaPyeong": 90,
    "address": "강서구 마곡동 · 아이파크디어반",
    "image": "assets/projects/work/it/secrab.jpg",
    "imageAlt": "씨크랩 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "nice-guys",
    "name": "멋진녀석들",
    "industryId": "it",
    "industry": "IT",
    "year": 2023,
    "areaPyeong": 80,
    "address": "오산시 부산동길",
    "image": "assets/projects/work/it/nice-guys.png",
    "imageAlt": "멋진녀석들 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "centralsoft",
    "name": "센트럴소프트",
    "industryId": "it",
    "industry": "IT",
    "year": 2023,
    "areaPyeong": 130,
    "address": "서울 송파구 문정동 · 문정역테라타워",
    "image": "assets/projects/work/it/centralsoft.jpg",
    "imageAlt": "센트럴소프트 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "vtech",
    "name": "브이테크",
    "industryId": "construction",
    "industry": "건설",
    "year": 2026,
    "areaPyeong": 100,
    "address": "서울 송파구 오금로 · 세기빌딩",
    "image": "assets/projects/work/construction/vtech.jpg",
    "imageAlt": "브이테크 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "carbon-reset",
    "name": "카본리셋",
    "industryId": "construction",
    "industry": "건설",
    "year": 2025,
    "areaPyeong": 160,
    "address": "광명 일직동 · GIDC 광명역",
    "image": "assets/projects/work/construction/carbon-reset.jpg",
    "imageAlt": "카본리셋 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "kl-system",
    "name": "케이엘공조",
    "industryId": "construction",
    "industry": "건설",
    "year": 2024,
    "areaPyeong": 90,
    "address": "수원 고색동",
    "image": "assets/projects/work/construction/kl-system.jpg",
    "imageAlt": "케이엘공조 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "sma",
    "name": "SM건축사사무소",
    "industryId": "construction",
    "industry": "건설",
    "year": 2022,
    "areaPyeong": 120,
    "address": "서울 서초구 방배동",
    "image": "assets/projects/work/construction/sma.png",
    "imageAlt": "SM건축사사무소 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "onejoon",
    "name": "원준",
    "industryId": "manufacturing",
    "industry": "제조",
    "year": 2026,
    "areaPyeong": 200,
    "address": "서초구 남부순환로 · 서희타워",
    "image": "assets/projects/work/manufacturing/onejoon.jpg",
    "imageAlt": "원준 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "lillem",
    "name": "릴엠",
    "industryId": "manufacturing",
    "industry": "제조",
    "year": 2024,
    "areaPyeong": 100,
    "address": "화성시 장안면",
    "image": "assets/projects/work/manufacturing/lillem.jpg",
    "imageAlt": "릴엠 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "gs-kor",
    "name": "지에스코",
    "industryId": "manufacturing",
    "industry": "제조",
    "year": 2024,
    "areaPyeong": 130,
    "address": "하남 망월동 · 미사강변스카이폴리스",
    "image": "assets/projects/work/manufacturing/gs-kor.jpg",
    "imageAlt": "지에스코 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "polaris-sewon",
    "name": "폴라리스 세원",
    "industryId": "manufacturing",
    "industry": "제조",
    "year": 2023,
    "areaPyeong": 180,
    "address": "평택 산단로 · 세원정공",
    "image": "assets/projects/work/manufacturing/polaris-sewon.jpg",
    "imageAlt": "폴라리스 세원 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "peaknic",
    "name": "피크닉",
    "industryId": "media",
    "industry": "미디어",
    "year": 2023,
    "areaPyeong": 120,
    "address": "판교 판교역로 · 서건타워",
    "image": "assets/projects/work/media/peaknic.png",
    "imageAlt": "피크닉 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "sangsang-square",
    "name": "상상스퀘어",
    "industryId": "media",
    "industry": "미디어",
    "year": 2022,
    "areaPyeong": 170,
    "address": "판교 판교역로 · 서건타워",
    "image": "assets/projects/work/media/sangsang-square.png",
    "imageAlt": "상상스퀘어 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "studio-bside",
    "name": "스튜디오비사이드",
    "industryId": "media",
    "industry": "미디어",
    "year": 2021,
    "areaPyeong": 180,
    "address": "판교 판교역로 · 미래에셋센터",
    "image": "assets/projects/work/media/studio-bside.png",
    "imageAlt": "스튜디오비사이드 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "hello-bobos",
    "name": "헬로우보보스",
    "industryId": "media",
    "industry": "미디어",
    "year": 2020,
    "areaPyeong": 150,
    "address": "판교 백현동 · 헬로보보스빌딩",
    "image": "assets/projects/work/media/hello-bobos.jpg",
    "imageAlt": "헬로우보보스 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "kyungil",
    "name": "경일감정평가법인",
    "industryId": "finance",
    "industry": "금융",
    "year": 2026,
    "areaPyeong": 100,
    "address": "수원 천천동 · 골든프라자",
    "image": "assets/projects/work/finance/kyungil.jpg",
    "imageAlt": "경일감정평가법인 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "helio-investment",
    "name": "힐리오인베스트먼트",
    "industryId": "finance",
    "industry": "금융",
    "year": 2025,
    "areaPyeong": 120,
    "address": "서울 강남구 삼성로 · K707빌딩",
    "image": "assets/projects/work/finance/helio-investment.jpg",
    "imageAlt": "힐리오인베스트먼트 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "accounting-firm-cheongin",
    "name": "회계법인청인",
    "industryId": "finance",
    "industry": "금융",
    "year": 2024,
    "areaPyeong": 90,
    "address": "강남구 역삼동 · 아이네트빌딩",
    "image": "assets/projects/work/finance/accounting-firm-cheongin.jpg",
    "imageAlt": "회계법인청인 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "a1-private-equity",
    "name": "에이원프라이빗에쿼티",
    "industryId": "finance",
    "industry": "금융",
    "year": 2021,
    "areaPyeong": 150,
    "address": "판교 판교역로 · 서건타워",
    "image": "assets/projects/work/finance/a1-private-equity.jpg",
    "imageAlt": "에이원프라이빗에쿼티 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "wea-cultural-space",
    "name": "위아 반려문화공간",
    "industryId": "service",
    "industry": "서비스",
    "year": 2025,
    "areaPyeong": 200,
    "address": "분당 율동공원",
    "image": "assets/projects/work/service/wea-cultural-space.jpg",
    "imageAlt": "위아 반려문화공간 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "man-of-action",
    "name": "맨 오브 액션",
    "industryId": "service",
    "industry": "서비스",
    "year": 2022,
    "areaPyeong": 110,
    "address": "판교 백현동 · 제이스타 빌딩",
    "image": "assets/projects/work/service/man-of-action.jpg",
    "imageAlt": "맨 오브 액션 오피스 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "pt-studio-yj",
    "name": "피티스튜디오 열정",
    "industryId": "service",
    "industry": "서비스",
    "year": 2022,
    "areaPyeong": 80,
    "address": "판교 테크노밸리 · 우림W시티",
    "image": "assets/projects/work/service/pt-studio-yj.png",
    "imageAlt": "피티스튜디오 열정 프로젝트",
    "mediaKind": "photo"
  },
  {
    "id": "fnc",
    "name": "에프엔씨",
    "industryId": "service",
    "industry": "서비스",
    "year": 2021,
    "areaPyeong": 130,
    "address": "경기 평택시 고덕면 · 센트리마",
    "image": "assets/projects/work/service/fnc.jpg",
    "imageAlt": "에프엔씨 오피스 프로젝트",
    "mediaKind": "photo"
  }
];
